<div id="header" class="navbar-static-top">
    <div class="container">
      <div class="row">
          <div class="col-xs-12">
              <div class="navbar-header">
                  <div class="navbar-brand">
                    <a href="/" class="logo"><img src="../images/logo.png" width="64" height="67"><span>TiDB</span></a>
                  </div>

          <!----        <div class="btn-group " id="group" role="group">
                      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          English
                          <span class="caret"></span>
                      </button>
                      <ul class="dropdown-menu">
                          <li class="active" ><a href="#" >Chinese</a></li>
                          <li><a href="#">English</a></li>
                      </ul>
                  </div> ----->

              </div>
              <div class=" hidden-xs">
                  <nav>
                      <ul class="outBtn nav navbar-nav navbar-right">
                          <li style=" width: 102px;">
                              <a class=""  href="javascript:;">

                                  <span class="btn_translate nav_open_btn flip in "><i></i></span>
                                  <img class="btn_translate flip out" src="../images/close_nav.png" width="35">

                              </a>
                          </li>
                      </ul>
                      <ul id="nav_open" class="nav navbar-nav navbar-right  ">
                          <li class="@@home"><a href="./index.html">HOME</a></li>
                          <li class="@@docs"><a href="./documentation.html">DOCS</a></li>
                          <li class="@@blog"><a href="#">BLOG</a></li>
                          <li class="@@about"><a href="./about.html">ABOUT</a></li>
                          <li class="nav_hidden" ><a href="#">GITHUT</a></li>
                          <li class="nav_hidden"><a href="#">SLACK</a> </li>
                          <li class="nav_hidden"><a href="#"> GET STARTED</a> </li>
                      </ul>
                  </nav>
              </div>
          </div>
      </div>
    </div>
    </div>